---
version: 0.0
os: linux
files:
  - source: target/Helloworld.war
    destination: /home/ubuntu/javaapp
hooks:
  AfterInstall:
     - location: script/install_dependencies
       timeout: 300
       runas: root
     - location: script/start_server
       timeout: 300
       runas: root
