version: 0.0
os: linux
files:
  - source: Helloworld.war
    destination: /home/ubuntu/javaapp
hooks:
  AfterInstall:
     - location: install_dependencies
       timeout: 300
       runas: root
     - location: start_server
       timeout: 300
       runas: root
